FROM node:iron-alpine3.20

WORKDIR /app

COPY package.json .

RUN npm install

ENV VITE_API_URL=http://localhost:8080

RUN npm i -g serve

COPY app/ .

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]